### ISSUE TITLE
Custom JSX module

### ISSUE THREAD

**Issue by dkirchhof** [rescript-lang/rewatch#130]
Hey,
I want to use rewatch in a project with a custom jsx module. But it isn't allowed.
The parser throws an error like: `unknown variant MyCustomJSX, expected react at line 25 column 24"`.

Cheers
Daniel

**Comment by zth** [comment]
Sounds like this should just be a matter of adapting Rewatch to use the same rules for that config as bsb currently does.

**Comment by dkirchhof** [comment]
:pray:

**Comment by rolandpeelen** [comment]
Assuming this is fixed @dkirchhof -- Feel free to reopen though :)

**Comment by dkirchhof** [comment]
No, the error still exists. Can't see any changes in the commits since I opened the issue.

**Comment by rolandpeelen** [comment]
@dkirchhof -- Can you give me a minimum reproducable example?

**Comment by dkirchhof** [comment]
Sure: Here it is:
https://github.com/dkirchhof/rewatch-example

just run `npm run build`

**Comment by rolandpeelen** [comment]
Fixed here: https://github.com/rescript-lang/rewatch/pull/143/commits/ae6c713095899546fd716a5652603b6797e81190

You can try installing [1.0.10-eac37e2.0](https://www.npmjs.com/package/@rolandpeelen/rewatch/v/1.0.10-eac37e2.0) which should fix it :)

**Comment by dkirchhof** [comment]
Thanks. I can build the source now.
Unfortunately there is a new issue (updated my repo). The compiler complains about jsx syntax. Might be an issue with the ppx similar to this one https://github.com/rescript-lang/rewatch/issues/104.
